app = "phonebook-ancient-moon-6798"
primary_region = "lhr"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = [ "gcr.io/paketo-buildpacks/nodejs" ]
image = "flyio/hellofly:latest"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"